# create a variable for token
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicHNldWRvIjoidGhvbWFzbGFmb3JnZUBnbWFpbC5jb20iLCJtb3RkZXBhc3NlIjoiJGFyZ29uMmlkJHY9MTkkbT02NTUzNix0PTMscD00JFVyU1lTYUc1Zks5TXkrbXc4RmQrVkEkMXkzMnMrcmVzTGhMazZUbUI5YkwzVzk4SnFxbkdIdXJySmhyajJPejZROCIsImlhdCI6MTc4MDU3ODI2MiwiZXhwIjoxNzgwNTg1NDYyfQ.3ZXuWnd7y7KP0jHYnyqymUPWMllp-mJaQQIgEGO8Qq4

### Register
POST http://localhost:1992/auth/local/register
Content-Type: application/json

{
  "data": {
    "pseudo": "thomaslaforge@gmail.com",
    "motdepasse": "admin1234"
  }
}


### Login
POST http://localhost:1992/auth
Content-Type: application/json

{
  "data": {
    "pseudo": "thomaslaforge@gmail.com",
    "motdepasse": "admin1234"
  }
}

### Get all voitures
GET http://localhost:1992/voitures
Authorization: Bearer {{token}}



### Get one voiture (
GET http://localhost:1992/voitures/1
Authorization: Bearer {{token}}

### Create voiture (body wrapped in data)
POST http://localhost:1992/voitures
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "data": {
    "name": "tesla",
    "price": 15000
  }
}

### Update voiture (PATCH, id in path, body wrapped in data)
PUT http://localhost:1992/voitures/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "data": {
    "name": "Peugeot 308",
    "price": 18000
  }
}

### Delete voiture (by query param)
DELETE http://localhost:1992/voitures/3
Authorization: Bearer {{token}}
