# create a variable for token
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicHNldWRvIjoidGhvbWFzbGFmb3JnZUBnbWFpbC5jb20iLCJtb3RkcGFzc2UiOiIkMmIkMTAkVkNCeURSY0lyM1hyVTVWeS96anhvZXFST1JIU2pqa1dyMm9uNDAudjlRSUpiTjlmR1hxcDYiLCJpYXQiOjE3ODA1MjYwODZ9.hVMt3rzu9pR-sRSbTcMm6owWqn_7zDDcC7586kGz9UM

### Register
POST http://localhost:1992/auth/local/register
Content-Type: application/json

{
  "pseudo": "thomaslaforge@gmail.com",
  "motdpasse": "admin1234"
}

### Login
POST http://localhost:1992/auth/local
Content-Type: application/json

{
  "pseudo": "thomaslaforge@gmail.com",
  "motdpasse": "admin1234"
}

### Get all voitures
GET http://localhost:1992/voitures/get-all
Authorization: Bearer {{token}}

### Get one voiture (by query param)
GET http://localhost:1992/voitures/get-this-one?id=1
Authorization: Bearer {{token}}

### Create voiture (body wrapped in data)
POST http://localhost:1992/voitures/create
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "data": {
    "name": "Peugeot 208",
    "price": 15000
  }
}

### Update voiture (PATCH, id in path, body wrapped in data)
PATCH http://localhost:1992/voitures/update/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "data": {
    "name": "Peugeot 308",
    "price": 18000
  }
}

### Delete voiture (by query param)
DELETE http://localhost:1992/voitures/delete?id=1
Authorization: Bearer {{token}}
